language: rust

sudo: required

services:
  - docker

before_install:
  - sudo apt-get -qq update
  - sudo apt-get install -y libpcap0.8-dev
rust:
  - stable
  - beta
  - nightly
matrix:
  allow_failures:
    - rust: nightly
after_success:
  - docker run --rm -it -v "/home/travis/build/Woutifier/packetcapr":/home/rust/src woutifier/rust-musl-builder cargo build --release --verbose
    

