[package]
name = "packetcapr"
version = "0.1.2"
authors = ["Wouter de Vries <wouter@wouter-web.nl>"]

[dependencies]
pcap = "0.5.7"
hyper = "0.9.10"
log = "0.3.6"
rustc-serialize = "0.3"
argparse = "*"
libc = "0.2.14"

[profile.dev]
debug = true
